name: io
description: |
  A Terminal / Command Line interface for bitrise.io,
  to manage your apps on bitrise.io right from your terminal / command line.
executable:
  osx: https://github.com/bitrise-io/bitrise-plugins-io/releases/download/0.0.5/bitrise-plugins-io-Darwin-x86_64
  linux: https://github.com/bitrise-io/bitrise-plugins-io/releases/download/0.0.5/bitrise-plugins-io-Linux-x86_64
trigger: ""
requirements:
- tool: bitrise
  min_version: 1.3.0
  max_version: ""
